# Generated by Django 5.1.1 on 2025-01-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0003_attendance_teacher_alter_attendance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterschedule',
            name='classroom_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
