# Generated by Django 5.1.1 on 2025-01-29 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0004_semesterschedule_classroom_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterschedule',
            name='classroom_number',
        ),
        migrations.RemoveField(
            model_name='semesterschedule',
            name='department',
        ),
        migrations.RemoveField(
            model_name='semesterschedule',
            name='details',
        ),
        migrations.RemoveField(
            model_name='semesterschedule',
            name='period',
        ),
        migrations.RemoveField(
            model_name='semesterschedule',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semesterschedule',
            name='subject',
        ),
        migrations.AddField(
            model_name='semesterschedule',
            name='course',
            field=models.ForeignKey(default='e21fd501-e739-4483-b07d-34cc6d200cec', on_delete=django.db.models.deletion.CASCADE, to='class_management.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semesterschedule',
            name='end_time',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semesterschedule',
            name='start_time',
            field=models.TimeField(default='9:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='teacher',
            field=models.ForeignKey(default='922b5bbd-628f-4126-abbe-723738746022', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
