# Generated by Django 5.1.1 on 2025-01-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0005_remove_semesterschedule_classroom_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterschedule',
            name='period',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
