# Generated by Django 5.1.1 on 2025-01-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0010_academiccalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
