# Generated by Django 5.1.1 on 2025-01-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0011_course_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class_management.department'),
        ),
    ]
