# Generated by Django 5.1.1 on 2025-02-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0012_section_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
