# Generated by Django 5.1.1 on 2025-02-02 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0013_remove_user_department_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterschedule',
            name='course',
        ),
        migrations.AddField(
            model_name='semesterschedule',
            name='classroom_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semesterschedule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_management.department'),
        ),
        migrations.AddField(
            model_name='semesterschedule',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semesterschedule',
            name='semester',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semesterschedule',
            name='subject',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
