# Generated by Django 5.1.1 on 2025-02-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0014_remove_semesterschedule_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(default='65120a32-7c0b-4269-adc4-57e94d95e6d9', on_delete=django.db.models.deletion.CASCADE, to='class_management.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
