# Generated by Django 5.1.1 on 2025-02-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0016_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
