# Generated by Django 5.1.1 on 2025-02-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0017_department_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterschedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_management.course'),
        ),
    ]
